### ISSUE TITLE
Changing to 12 hour format does not work

### ISSUE THREAD

**Issue by Kirugaming** [bridgeland-hs/bridgeland-hs.github.io#1]
When the switch button is pressed, it does not change the time to 12-hour format but instead returns to its off position.
---
![problem](https://user-images.githubusercontent.com/29207998/139566759-99128a01-2a67-4e41-b70f-a974186bbeff.gif)

**Comment by funnyboy-roks** [comment]
Ah, I kinda forgot about that.  I'll look into it

**Comment by funnyboy-roks** [comment]
This should be fixed as of d8b33ed6fd6c8b26746d55f3dd787f7b214718d9
